name: Rails CI/CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

    - name: Deploy to EC2
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        HOST_NAME: ${{ secrets.HOST_NAME }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} << 'EOF'
          cd beGitter
          git pull origin main
          ~/.rbenv/shims/bundle install
          ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production
          ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production

          # Pumaを再起動（systemd で管理してるなら）
          sudo systemctl restart puma
        EOF
